Quality check: Metadata updates in AAC Content Pattern Library
MicrosoftDocs/content-templates pull request #43
Opened 2024-09-23 21:25 UTC by v-stsavell

This PR updates metadata in the AAC templates. Here's the [ADO work item](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314493).

2024-09-23 21:33 UTC, ShannonLeavitt commented on templates/org/aac/aac-topic-landing-page.md
>  ---
```suggestion
ms.subservice: 
---
```
Adding an empty slug here

2024-09-23 21:37 UTC, ShannonLeavitt commented on templates/org/aac/aac-topic-landing-page.md
>  author:
```suggestion
author: <Contributor's GitHub username>
ms.author: <Contributor's Microsoft alias> 
```

2024-09-23 21:48 UTC, v-stsavell commented
@ckittel - requesting review. Thanks!

2024-09-25 15:10 UTC, ckittel requested changes
I don't know what https://github.com/v-stsavell/content-templates/blob/metadata-update/templates/org/aac/aac-architecture-guide-browse.yml is -- I don't THINK it's used anywhere, but just for completeness, can you please change `ms.service` to `azure-architecture-center` and `ms.subservice` to `architecture-guide`  in that file - You can make the `ms.date` and author changes as well if you wish.

2024-09-25 15:10 UTC, ckittel commented on templates/org/aac/aac-topic-landing-page.md
> +ms.subservice:
```suggestion
```

2024-09-25 15:10 UTC, ckittel commented on templates/org/aac/aac-browser-header.yml
> +  ms.topic: <For an example workload, use `example-scenario`; for a reference architecture, use `reference-architecture`; for a solution idea, use `solution-idea`.>
```suggestion
  ms.topic: <For an example workload, use example-scenario; for a reference architecture, use reference-architecture; for a solution idea, use solution-idea>
```

2024-09-25 15:10 UTC, ckittel commented on templates/org/aac/aac-browser-header.yml
> +  ms.subservice: <For an example workload, use `example-scenario`; for a reference architecture, use `reference-architecture`; for a solution idea, use `solution-idea`.>
```suggestion
  ms.subservice: <For an example workload, use example-scenario; for a reference architecture, use reference-architecture; for a solution idea, use solution-idea>
```

2024-09-25 15:29 UTC, ckittel approved these changes
Thanks!

2024-09-25 15:30 UTC, ckittel commented
#sign-off (though, that doesn't work in this repo -- it's the thought that counts).  Make sure you @ whoever has permissions in this repo to merge.  I don't remember who, maybe check old PRs.

2024-09-25 15:50 UTC, v-stsavell commented
Hi @mattbriggs - I see you've previously merged PRs in this repo. Could you merge, or direct me to who can? Thanks!

2024-09-25 18:45 UTC, mattbriggs approved these changes

2024-09-25 18:45 UTC, merged